name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unittest:
    name: Unit tests - ${{ matrix.PYTHON_VERSION }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.10"]
    defaults:
      run:
        # see https://github.com/conda-incubator/setup-miniconda/#important
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Conda env
        uses: mamba-org/provision-with-micromamba@e2b397b12d0a38069451664382b769c9456e3d6d
        with:
          cache-env: true
          extra-specs: |
            python=${{ matrix.PYTHON_VERSION }}
      - name: Install repository
        run: python -m pip install --no-build-isolation --no-deps --disable-pip-version-check -e .
      - name: Pytest
        run: pytest tests

  pre-commit-checks:
    name: "Pre-commit checks - Python 3.8"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.1.0
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run pre-commit checks
        uses: pre-commit/action@v2.0.0